package models;

public enum ErrorCode {
    ITEM_UNAVAILABLE,
    RESTAURANT_CLOSED,
    ITEM_NOT_FOUND,
    RESTAURANT_NOT_FOUND,
    USER_DOES_NOT_EXIST,
    ORDER_NOT_FOUND,
    RESTAURANT_ALREADY_EXISTS;
}
